# Generated by Django 2.1.5 on 2019-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
    ]
