# Generated by Django 2.1.5 on 2019-04-10 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190410_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='poster_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
