# Generated by Django 2.1.5 on 2019-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190411_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_no',
        ),
        migrations.AlterField(
            model_name='events',
            name='poster_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
