# Generated by Django 2.1.5 on 2019-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190419_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='phone_no',
            field=models.IntegerField(default=9999999999),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(default=9999999999),
        ),
    ]
