# Generated by Django 2.1.5 on 2019-04-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190419_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='email_id',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
