# Generated by Django 2.1.5 on 2019-04-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190419_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='email_id',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone_no',
            field=models.IntegerField(default=9999999999, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(default=9999999999, max_length=10),
        ),
    ]
