# Generated by Django 2.1.5 on 2019-04-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20190419_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
