# Generated by Django 2.1.5 on 2019-04-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20190419_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
