# Generated by Django 2.1.5 on 2019-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20190419_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='phone_no',
            field=models.IntegerField(default=9999999999),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(default=9999999999),
        ),
    ]
