# Generated by Django 2.1.5 on 2019-04-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20190419_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_div',
            field=models.CharField(choices=[('w', 'workshop'), ('comp', 'competition'), ('conf', 'conference')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='society',
            field=models.CharField(choices=[('TNT', 'Thapar Nautanki Team'), ('SCIM', 'Scimatics'), ('IETE', 'The Institution of Electronics and Telecommunication Engineers'), ('CCS', 'Creative Computing Society'), ('LitSoc', 'Literary Society'), ('Mudra', 'Music and Drama Society'), ('FAPS', 'FINE ARTS AND PHOTOGRAPHY SOCIETY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('part_id', 'event_id')},
        ),
    ]
