# Generated by Django 2.1.5 on 2019-04-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20190423_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.Organizer'),
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together={('organizer_id', 'event_name')},
        ),
    ]
