# Generated by Django 2.1.5 on 2019-04-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20190424_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='ident_no',
        ),
        migrations.AddField(
            model_name='events',
            name='id',
            field=models.AutoField(auto_created=True, default='xyz', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='id',
            field=models.AutoField(auto_created=True, default='xyz', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Organizer'),
        ),
    ]
