# Generated by Django 2.1.5 on 2019-04-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20190424_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='id',
        ),
        migrations.AddField(
            model_name='organizer',
            name='ident_no',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.Organizer'),
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='events',
            name='id',
        ),
    ]
