# Generated by Django 2.1.5 on 2019-04-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20190424_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='id',
            field=models.AutoField(auto_created=True, default='abc', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_div',
            field=models.CharField(choices=[('w', 'workshop'), ('comp', 'competition'), ('conf', 'conference')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('s', 'Sports'), ('t', 'Technical'), ('c', 'Cultural')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Organizer'),
        ),
        migrations.AlterField(
            model_name='events',
            name='poster_img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
