# Generated by Django 2.1.5 on 2019-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20190424_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.CharField(default='<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>', editable=False, max_length=20),
        ),
    ]
