# Generated by Django 2.1.5 on 2019-04-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20190424_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_div',
            field=models.CharField(choices=[('w', 'workshop'), ('comp', 'competition'), ('conf', 'conference')], max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('s', 'Sports'), ('t', 'Technical'), ('c', 'Cultural')], max_length=20),
        ),
    ]
